spring:
   datasource:
      url: jdbc:oracle:thin:@localhost:1521:system
      username: catalogo
      password: catalogo
      driver-class-name: oracle.jdbc.driver.OracleDriver
   security:
      user:
         name: root
         password: s3cr3t
   application:
      name: smartphone-catalog
   profiles:
      active: development
   cloud:
      config:
         uri: http://localhost:8888
         username: root
         password: s3cr3t
server:
  port: 8080
logging:
   level:
      org:
         hibernate:
            SQL: debug
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
